version: "3.9"

services:
  mula:
    build:
      context: .
      args:
        PIP_PACKAGES: requirements-dev.txt
    env_file:
      - .ci/.env.test
    volumes:
      - .:/app/scheduler

  mula_integration:
    build:
      context: .
      args:
        PIP_PACKAGES: requirements-dev.txt
    command: python -m unittest discover tests/integration
    env_file:
      - .ci/.env.test
    volumes:
      - .:/app/scheduler
    depends_on:
      - ci_katalogus
      - ci_octopoes_api

  ci_katalogus:
    build:
      context: ..
      dockerfile: nl-rt-tim-abang-boefjes/Dockerfile
    command: [ "python", "-m", "uvicorn", "--host", "0.0.0.0", "katalogus.api:app" ]

  ci_octopoes_api:
    build:
      context: ..
      dockerfile: nl-rt-tim-abang-octopoes/Dockerfile
    command: uvicorn octopoes.api:app --host 0.0.0.0 --port 80

  ci_boefje:
    build:
      context: .
      dockerfile: nl-rt-tim-abang-boefjes/Dockerfile
    command: python3 -m bin.worker boefje
