version: "3.9"

services:
  mula:
    build:
      context: .
      args:
        PIP_PACKAGES: requirements-dev.txt
    env_file:
      - .ci/.env.test
    volumes:
      - .:/app/scheduler

  mula_integration:
    build:
      context: .
      args:
        PIP_PACKAGES: requirements-dev.txt
    command: python -m unittest discover tests/integration
    env_file:
      - .ci/.env.test
    volumes:
      - .:/app/scheduler
