name: package bytes

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - name: Replace version number with release version
        run: sed -ibak "s/version=.*/version=\"${RELEASE_VERSION}\",/" ./setup.py

      - name: Create bytes release
        run:  tar -cvzf ../mula_${{ env.RELEASE_VERSION }}.tar.gz --exclude=./.git* .

      - name: Upload bytes tar
        uses: actions/upload-artifact@v1
        with:
          name: mula_${{ env.RELEASE_VERSION }}
          path: ../mula_${{ env.RELEASE_VERSION }}.tar.gz
