name: Run the test suite

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: ['3.8', '3.9', '3.10', '3.11']

    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the images
        run: DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f base.yml -f .ci/docker-compose.yml build --build-arg PYTHON_VERSION=${{ matrix.version }}

      - name: Run unit tests
        run: make utest

      - name: Run integration tests
        run: make itest
