name: Run the test suite


on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run unit tests
        run: make utest

      - name: Run integration tests
        run: make itest
